// Code generated by sqlc. DO NOT EDIT.
// source: refresh_tokens.sql

package db

import (
	"context"
)

const clearRefreshTokens = `-- name: ClearRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) ClearRefreshTokens(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, clearRefreshTokens, userID)
	return err
}

const newRefreshToken = `-- name: NewRefreshToken :exec
INSERT INTO refresh_tokens (
  user_id, token
) VALUES (
  $1, $2
)
`

type NewRefreshTokenParams struct {
	UserID string `json:"user_id"`
	Token  string `json:"token"`
}

func (q *Queries) NewRefreshToken(ctx context.Context, arg NewRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, newRefreshToken, arg.UserID, arg.Token)
	return err
}
